theme: minima
title: GAO's Cafe
description: Talk about AI, AR and AW.
header_pages:
  - about.md

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/gao-shaofei" }
    - { platform: twitter, user_url: "https://x.com/gaoshaofei" }

google_analytics: UA-NNNNNNNN-N
show_excerpts: true