theme: jekyll-theme-minimal
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: gao's homepage
description: Talk about AI, AR and AW!
