theme: minima
title: GAO's Cafe
description: Talk about AI, AR and AW.
header_pages:
  - about.md
  - index.md # Ensure the homepage is listed here

languages:
  en: "English"
  zh: "中文"

defaults:
  - scope:
      path: ""
      lang: "en"
    values:
      layout: "home" # Ensure the layout is set to "home" for the homepage
  - scope:
      path: "zh"
      lang: "zh"
    values:
      layout: "home" # Ensure the layout is set to "home" for the homepage
