theme: minima
title: GAO's Cafe
description: Talk about AI, AR and AW.
header_pages:
  - about.md

languages:
  en: "English"
  zh: "中文"

defaults:
  - scope:
      path: ""
      lang: "en"
    values:
      layout: "default"
  - scope:
      path: "zh"
      lang: "zh"
    values:
      layout: "default"
